### ISSUE TITLE
Permission problems when building wallet in linux

### ISSUE THREAD

**Issue by tvl83** [LIMXTEC/LasVegasCoin2#1]
I am currently doing a tutorial on how to build a block chain explorer with javascript on liveed.tv https://www.liveedu.tv/tvle83/2PY30-how-to-create-a-blockchain-explorer-with-javascript/ and chose your coin to use for the coin on the tutorial.

I am using an ubuntu server and have to build the wallet, of course. 

I am running into permission issues the first one was with autogen.sh it was not executable so I did a `chmod 755` on it. 

I also had to chmod 755 on the leveldb folder in the source directory and the share directory. 

I just wanted to report this because it might be a problem for others who want to build the coin on linux.

**Comment by tvl83** [comment]
The `make install` command has permission errors as well.

**Comment by TheJimmyH** [comment]
Did this ever get completed?  I would LOVE to be able to set up a remote VPS on a Ubuntu server for this coin!
